apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: devops-platform
  labels:
    app: backend

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: jsdaya2211/backend-image:2026.06.22-0840
        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: backend-config

        - secretRef:
            name: backend-secret

        readinessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3 

        startupProbe:
          httpGet:
            path: /health
            port: 5000

          failureThreshold: 30
          periodSeconds: 10

        securityContext:
          allowPrivilegeEscalation: false    


        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"