apiVersion: v1

kind: Secret

metadata:
  name: mysql-secret
  namespace: devops-platform

  labels:
    app: mysql

type: Opaque

data:
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-database: ZGV2b3BzZGI=
  mysql-user: YXBwdXNlcg==